services:
  database:
    image: postgres:16.3
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database-data:/var/lib/postgresql/data
    cpu_count: 2

volumes:
  database: {}
